package model;
// Generated Nov 11, 2021 2:40:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer idCategory;
     private String name;
     private Set categoryMoives = new HashSet(0);

    public Category() {
    }

	
    public Category(String name) {
        this.name = name;
    }
    public Category(String name, Set categoryMoives) {
       this.name = name;
       this.categoryMoives = categoryMoives;
    }
   
    public Integer getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCategoryMoives() {
        return this.categoryMoives;
    }
    
    public void setCategoryMoives(Set categoryMoives) {
        this.categoryMoives = categoryMoives;
    }

    @Override
    public String toString() {
        return this.name;
    }
}


