package model;
// Generated Nov 11, 2021 2:40:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Filmtype generated by hbm2java
 */
public class Filmtype  implements java.io.Serializable {


     private Integer idFilmType;
     private String name;
     private Set movies = new HashSet(0);

    public Filmtype() {
    }

	
    public Filmtype(String name) {
        this.name = name;
    }
    public Filmtype(String name, Set movies) {
       this.name = name;
       this.movies = movies;
    }
   
    public Integer getIdFilmType() {
        return this.idFilmType;
    }
    
    public void setIdFilmType(Integer idFilmType) {
        this.idFilmType = idFilmType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getMovies() {
        return this.movies;
    }
    
    public void setMovies(Set movies) {
        this.movies = movies;
    }

    @Override
    public String toString() {
        return this.name;
    }




}


