package model;
// Generated Nov 11, 2021 2:40:31 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MovieAdmin generated by hbm2java
 */
public class MovieAdmin  implements java.io.Serializable {


     private Integer idMovieAdmin;
     private Admin admin;
     private Movie movie;
     private Date dateAction;
     private String title;

    public MovieAdmin() {
    }

    public MovieAdmin(Admin admin, Movie movie, Date dateAction, String title) {
       this.admin = admin;
       this.movie = movie;
       this.dateAction = dateAction;
       this.title = title;
    }
   
    public Integer getIdMovieAdmin() {
        return this.idMovieAdmin;
    }
    
    public void setIdMovieAdmin(Integer idMovieAdmin) {
        this.idMovieAdmin = idMovieAdmin;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public Movie getMovie() {
        return this.movie;
    }
    
    public void setMovie(Movie movie) {
        this.movie = movie;
    }
    public Date getDateAction() {
        return this.dateAction;
    }
    
    public void setDateAction(Date dateAction) {
        this.dateAction = dateAction;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

 





}


